/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActionsMenu: typeof import('./src/components/ui/global/ActionsMenu.vue')['default']
    Avatar: typeof import('./src/components/ui/global/Avatar.vue')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    CardContent: typeof import('./src/components/ui/local/CardContent.vue')['default']
    Carousel: typeof import('primevue/carousel')['default']
    Checkbox: typeof import('./src/components/ui/global/Checkbox.vue')['default']
    DateTimePicker: typeof import('./src/components/ui/global/DateTimePicker.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    EmptyCard: typeof import('./src/components/ui/local/EmptyCard.vue')['default']
    ErrorToast: typeof import('./src/components/ui/global/ErrorToast.vue')['default']
    IconWrapper: typeof import('./src/components/ui/local/IconWrapper.vue')['default']
    Input: typeof import('./src/components/ui/global/Input.vue')['default']
    InputNumber: typeof import('./src/components/ui/global/InputNumber.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Menu: typeof import('primevue/menu')['default']
    MultiSelect: typeof import('./src/components/ui/global/MultiSelect.vue')['default']
    OptionsDropdown: typeof import('./src/components/ui/local/OptionsDropdown.vue')['default']
    Password: typeof import('./src/components/ui/global/Password.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./src/components/ui/global/Select.vue')['default']
    Skeleton: typeof import('primevue/skeleton')['default']
    SuccessToast: typeof import('./src/components/ui/global/SuccessToast.vue')['default']
    Switch: typeof import('./src/components/ui/global/Switch.vue')['default']
    Tag: typeof import('primevue/tag')['default']
    Text: typeof import('./src/components/ui/global/Text.vue')['default']
  }
}
